spring.datasource.url=jdbc:postgresql://localhost:5432/hirecrux_db
spring.datasource.username=monika
spring.datasource.password=monika123

#java cls name in db driver and coneection between spring and postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA-- maping between entities and tables
#validate the existing table
spring.jpa.hibernate.ddl-auto=validate

#print sql query in cmd
spring.jpa.show-sql=true

#make sql md in terminal formate clean
spring.jpa.properties.hibernate.format_sql=true

#Tells Hibernate exactly which SQL "dialect" to speak optimize sql query
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
#logging.level.org.springframework.security=TRACE